name: Lint, Build, and Test

on:
  workflow_dispatch:
    
  push:
    branches:
      - Develop
      - Main
  pull_request:
    branches:
      - Develop
      - Main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install PNPM
      run: npm install -g pnpm 

    - name: Install Dependencies
      run: pnpm install
    
    - name: Build App
      run: pnpm build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist
  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install PNPM
      run: npm install -g pnpm 

    - name: Install Dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint

  test:
    needs: [build, lint]
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
  
    - name: Install PNPM
      run: npm install -g pnpm 
  
    - name: Install Dependencies
      run: pnpm install

    - name: Test
      run: pnpm test
    
  uploadBuild:
    needs: test
    name: Upload Build to S3
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Upload build to S3
      run: aws s3 cp build.zip $BUCKET_LOCATION/${{github.sha}}/
      env: 
        BUCKET_LOCATION: ${{secrets.AWS_S3_PROJECT_DIRECTORY}}