name: Lint, Build, and Test

on:
  workflow_dispatch:
    
  push:
    branches:
      - Develop
      - Main
  pull_request:
    branches:
      - Develop
      - Main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install PNPM
      run: npm install -g pnpm 

    - name: Install Dependencies
      run: pnpm install
    
    - name: Build App
      run: pnpm build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Install PNPM
      run: npm install -g pnpm 

    - name: Install Dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint